/** @format */

module.exports = {
  // theme: {
  //   '@ant-prefix': 'myAnt',
  //   // 主题色
  //   '@primary-color': '#275EFF',
  //   '@success-color': '#67b67d',
  //   '@info-color': '#af9d9d',
  //   '@warning-color': '#cf9616',
  //   '@error-color': '#ee190c',
  //   '@highlight-color': '#d46060',
  //   '@processing-color': '@primary-color',
  //   '@body-background': '#695a5a',
  //   // label的文本颜色
  //   '@heading-color': '#967070',
  //   // 普通文本的颜色
  //   '@text-color': '#160d0d',
  //   // 表单label中的toolip颜色，和各种移除icon浮动上去的颜色
  //   '@text-color-secondary': '#474242',
  //   // 在暗黑色系下的文字颜色或者选择了一部分文字之后的颜色
  //   '@text-color-inverse': '#290404',
  //   '@heading-color-dark': '#745e5e',
  //   '@text-color-dark': '#693939',
  //   '@text-color-secondary-dark': '#463838',
  //   // 选择了一部分文字的背景颜色
  //   '@text-selection-bg': '#b3a7a7',
  //   '@border-color-base': '#dedede',
  //   '@border-color-split': '#dedede',
  //   '@layout-body-background': '#fafafa',
  //   '@border-radius-base': '0',
  //   '@border-radius-sm': '0',
  //   '@outline-width': '0',
  //   '@outline-color': '#737373',
  //   '@background-color-base': 'hsv(0, 0, 96%)',
  //   '@btn-default-bg': '#fafafa',
  //   '@btn-default-border': '#dedede',
  //   '@radio-button-bg': 'transparent',
  //   '@radio-button-checked-bg': 'transparent',
  //   '@form-item-margin-bottom': '16px',
  //   '@input-height-lg': '36px',
  //   '@progress-radius': '0',
  //   '@table-header-bg': '#fafafa',
  //   '@table-row-hover-bg': '#fafafa',
  //   '@table-padding-vertical': '15px',
  //   '@tabs-card-gutter': '-1px',
  //   '@tabs-card-tab-active-border-top': '2px solid @primary-color',
  //   '@switch-color': '@success-color',
  //   '@breadcrumb-base-color': '@text-color',
  //   '@breadcrumb-last-item-color': '@text-color-secondary',
  //   '@slider-handle-border-width': '1px',
  //   '@slider-handle-shadow': '1px 1px 4px 0 rgba(0,0,0,.13)',
  //   '@slider-track-background-color': '@primary-color',
  //   '@slider-track-background-color-hover': '@primary-color',
  //   '@slider-handle-color': '#dedede',
  //   '@slider-handle-color-hover': '#dedede',
  //   '@slider-handle-color-focus': '#dedede',
  //   '@slider-handle-color-focus-shadow': 'transparent',
  //   '@slider-handle-color-tooltip-open': '#ddd',
  //   '@alert-success-border-color': '#dff4e5',
  //   '@alert-success-bg-color': '#dff4e5',
  //   '@alert-info-border-color': '#e5f3ff',
  //   '@alert-info-bg-color': '#e5f3ff',
  //   '@alert-warning-border-color': '#fff7db',
  //   '@alert-warning-bg-color': '#fff7db',
  //   '@alert-error-border-color': '#fcebea',
  //   '@alert-error-bg-color': '#fcebea',
  //   '@font-family': 'PingFangSC-Regular, PingFang SC',
  //   // font-variant-base-设置小型字母字体，相当于设置upper或者lowwer的字体
  //   '@font-size-base': '14px',
  //   '@disabled-color': '#bebebe',
  //   // 功能类似于text-decoration
  //   '@link-decoration': 'overline',

  //   '@input-placeholder-color': '#bebebe',
  //   '@input-hover-border-color': '#186bff',
  //   // 改动了表单元素hover和active的颜色
  //   '@primary-color-hover': '#186bff',
  //   '@primary-color-active': '#186bff'
  // }
  theme: {
    '@ant-prefix': 'myAnt',
    '@primary-color': '#186bff',
    '@success-color': '#21d69c',
    '@info-color': '#186bff',
    '@warning-color': '#ffa902',
    '@error-color': '#f5222d',
    '@highlight-color': '#1890ff',
    '@processing-color': '@primary-color',
    '@icon-color-hover': '#408cff',
    '@heading-color': '#303133',
    '@text-color': '#303133',
    '@text-color-secondary': '#b6b6b6',
    '@border-color-base': '#dfdfdf',
    '@border-color-split': '#dfdfdf',
    '@layout-body-background': '#fafafa',
    '@font-family':
      'PingFang SC、Hiragino Sans GB、Microsoft YaHei、Helvetica Neue、Helvetica、Arial',
    '@border-radius-base': '0',
    '@border-radius-sm': '0',
    '@disabled-color': '#dcdcdc',
    '@outline-width': '0px',
    '@outline-color': '#737373',
    '@background-color-base': 'hsv(0, 0, 96%)',
    '@shadow-color': '#000000',
    '@shadow-2':
      '0 4px 10px 0px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08),',
    '@btn-primary-color': '#ffffff',
    '@btn-default-bg': '#fafafa',
    '@btn-default-border': '#dedede',
    '@radio-button-bg': 'transparent',
    '@radio-button-checked-bg': 'transparent',
    '@form-item-margin-bottom': '16px',
    '@input-height-lg': '36px',
    '@input-number-handler-active-bg': '#ffffff',
    '@input-hover-border-color': '#408CFF',
    '@tooltip-arrow-width': '8px',
    '@popover-arrow-width': '8px',
    '@progress-radius': '0',
    '@table-header-bg': '#fafafa',
    '@table-row-hover-bg': '#fafafa',
    '@table-padding-vertical': '15px',
    '@tabs-card-gutter': '-1px',
    '@tabs-card-tab-active-border-top': '2px solid @primary-color',
    '@switch-color': '@success-color',
    '@breadcrumb-base-color': '@text-color',
    '@breadcrumb-last-item-color': '@text-color-secondary',
    '@slider-handle-border-width': '1px',
    '@slider-handle-shadow': '1px 1px 4px 0 rgba(0,0,0,.13)',
    '@slider-track-background-color': '@primary-color',
    '@slider-track-background-color-hover': '@primary-color',
    '@slider-handle-color': '#dedede',
    '@slider-handle-color-hover': '#dedede',
    '@slider-handle-color-focus': '#dedede',
    '@slider-handle-color-focus-shadow': 'transparent',
    '@slider-handle-color-tooltip-open': '#ddd',
    '@alert-success-border-color': 'B7EB8F',
    '@alert-success-bg-color': '#dff4e5',
    '@alert-info-border-color': '#e5f3ff',
    '@alert-info-bg-color': '#e5f3ff',
    '@alert-warning-border-color': '#fff7db',
    '@alert-warning-bg-color': '#fff7db',
    '@alert-error-border-color': '#fcebea',
    '@alert-error-bg-color': '#fcebea'
  }
};
